server:
  port: 9001

netty:
  port: 8000

spring:
  data:
    redis:
      host: 47.120.12.23
      port: 6379
      password: "000415"
      lettuce:
        pool:
          max-wait: 100000
          max-idle: 10
          max-active: 100
      timeout: 50000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iMusic?useUnicode=true&characterEncoding=utf8
    username: root
    password: Chang687501
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 47.120.12.23
    port: 5672
    username: admin
    password: As603888
  mail:
    port: 465
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 847024724@qq.com
    password: bddqhyinznwwbfba
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
    code:
      pre: CODE
      expire: 300

mybatis-plus:
  type-aliases-package: com.studio.music.song.model.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com: debug

group:
  pre: GROUP
  expire: 900
