server:
  port: 9000

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iMusic?useUnicode=true&characterEncoding=utf8
    username: root
    password: Chang687501

mybatis-plus:
  type-aliases-package: com.studio.music.auth.model.pojo
  configuration:
    map-underscore-to-camel-case: false